### ISSUE TITLE
Restore with Seedwords and wrong date does not trigger an error

### ISSUE THREAD

**Issue by ManfredKarrer** [vinumeris/lighthouse#188]
When using a wrong creation date when restoring the wallet from seed words, it succeeds without any error. Not sure which consequences a different creation time has in the HD wallet creation, at least I could transfer Bitcoin out of a restored wallet with a wrong creation date.

**Comment by mikehearn** [comment]
Unfortunately the seed words spec is designed for web wallets, so it does not include the seed birthday in it. There's no way to avoid this. MultiBit gets you to write down the date in a special custom format that includes a checksum so it's harder for users to do the wrong date, but I'm not sure how often this should come up. People are supposed to write down both.

If the date is wrong then not all of the block chain will be scanned and you may miss transactions. In that case, just reset it with the right date and the balance should appear properly.

**Comment by ManfredKarrer** [comment]
Ah ok, so its a minor issue if that goes wrong. Thanks for the info.

**Comment by mikehearn** [comment]
Well, I wouldn't say it's a minor issue even though it's easy to recover from. I really, really wish the words algorithm had been defined to include a birthday. Unfortunately the spec authors sort of barrelled ahead without taking that feedback into account, because their wallet architecture didn't need it :(

However, long term it doesn't matter. Long term the right direction we all need to go is to use the seed words as an AES key to encrypt a wallet backup that's sitting in the cloud (and/or ALSO be the seed for the private keys). That way you can restore wallet metadata and not just keys.
